Update

diff --git a/scripts/.local/bin/gr b/scripts/.local/bin/gr
--- a/scripts/.local/bin/gr
+++ b/scripts/.local/bin/gr
@@ -5,7 +5,26 @@
 # 1. Search for text in files using Ripgrep
 # 2. Interactively narrow down the list using fzf
 # 3. Open the file in Vim
-[[ $1 = "--hidden" || $1 = "-h" ]] && extra_args=--hidden && shift
+extra_args=""
+while getopts ":hn" opt; do
+  case ${opt} in
+    h )
+      extra_args="$extra_args --hidden"
+      ;;
+    n )
+      extra_args="$extra_args --no-ignore"
+      ;;
+    \? )
+      echo "Invalid option: -$OPTARG" 1>&2
+      exit 1
+      ;;
+    : )
+      echo "Option -$OPTARG requires an argument." 1>&2
+      exit 1
+      ;;
+  esac
+done
+shift $((OPTIND -1))
 
 IFS=: read -ra selected < <(
   rg --color=always --line-number --no-heading --smart-case ${extra_args:-} "${*:-}" |
